# This is a basic workflow to help you get started with Actions

name: Deployment for Production

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:       
  
  job_one:
    name: Deploy
    runs-on: [self-hosted, Linux, X64]
    steps:
    - name: testing saltmaster ssh connection
      uses: garygrossgarten/github-action-ssh@v0.6.3
      with:
        host: ${{ secrets.SALTMASTERIP }}
        username: DevOps
        privateKey: ${{ secrets.OCT_DEC }}
        command: |
           sudo rm -rf /srv/salt
           sudo rm -rf /home/DevOps/jobs
           cd /SaltStack
           sudo git fetch origin
           sudo git reset --hard origin/master
           sudo mv salt /srv
           sudo mv jobs /home/DevOps
           sudo chmod -R +x /home/DevOps/jobs/*
           sudo salt-run saltutil.sync_all
